"""SDK settings resolution: explicit args -> env vars -> derived defaults.

Every setting in the Checkrd Python SDK resolves through the same precedence
chain, matching the convention used by Stripe, Anthropic, OpenAI, and Sentry::

    explicit keyword argument  >  environment variable  >  derived default

Keeping the resolution logic in one place (instead of threading individual
values through the stack) makes the SDK trivial to test and means the
zero-config path ``wrap(httpx.Client())`` behaves exactly like the fully
explicit one when the corresponding environment variables are set.

Recognized environment variables:

- ``CHECKRD_API_KEY`` — authentication key for the control plane.
- ``CHECKRD_BASE_URL`` — control plane base URL (e.g. ``https://api.checkrd.io``).
- ``CHECKRD_AGENT_ID`` — stable identifier for this agent / service.
- ``CHECKRD_ENFORCE`` — ``1``/``true``/``yes``/``on`` to force enforcement,
  anything else to force observation mode. Overrides the ``"auto"`` default
  but not an explicit ``True``/``False`` passed to :func:`checkrd.wrap`.
- ``CHECKRD_DISABLED`` — ``1``/``true``/``yes``/``on`` to bypass the SDK
  entirely (no WASM init, no transport swap).
- ``CHECKRD_AGENT_KEY`` — base64 Ed25519 private key for production identity
  (consumed by :class:`checkrd.LocalIdentity.from_env`, not this module).

The fallback chain for ``agent_id`` matches what ``sentry_sdk`` and
``ddtrace`` use for service names: first an explicit env var, then a list
of well-known PaaS service-name env vars, then ``{script}-{hostname}``,
then a logged random fallback.
"""

from __future__ import annotations

import logging
import os
import socket
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Mapping, Optional, Union
from urllib.parse import urlparse

logger = logging.getLogger("checkrd")


# ---------------------------------------------------------------------------
# Public constants
# ---------------------------------------------------------------------------

#: Environment variable for the control-plane API key. Matches the
#: ``{PROJECT}_API_KEY`` convention used by Stripe, Anthropic, and OpenAI.
ENV_API_KEY = "CHECKRD_API_KEY"

#: Environment variable for the control-plane base URL. Matches the
#: ``{PROJECT}_BASE_URL`` convention used by Anthropic and OpenAI.
ENV_BASE_URL = "CHECKRD_BASE_URL"

#: Environment variable for the stable agent identifier.
ENV_AGENT_ID = "CHECKRD_AGENT_ID"

#: Environment variable for forcing enforcement on/off. Overrides
#: :data:`EnforceMode` ``"auto"`` but never an explicit ``True``/``False``.
ENV_ENFORCE = "CHECKRD_ENFORCE"

#: Environment variable to disable the SDK entirely. When set to a truthy
#: value, ``wrap()`` returns the client unchanged.
ENV_DISABLED = "CHECKRD_DISABLED"

#: Environment variable for the dashboard base URL. Used to generate
#: deep links in :class:`CheckrdPolicyDenied` error messages.
ENV_DASHBOARD_URL = "CHECKRD_DASHBOARD_URL"

#: Environment variable to enable debug logging. When truthy, the SDK
#: logs a per-request evaluation trace at DEBUG level.
ENV_DEBUG = "CHECKRD_DEBUG"

#: Environment variable to allow non-HTTPS control-plane URLs
#: (e.g. ``http://localhost:8080``). Explicit opt-in for local development.
#: **Never set this in production** — API keys and signed telemetry would be
#: sent in plaintext.
ENV_ALLOW_INSECURE_HTTP = "CHECKRD_ALLOW_INSECURE_HTTP"

#: Environment variable to skip WASM binary integrity verification.
#: **Test-only.** The hash file ``_wasm_integrity.py`` is regenerated by
#: ``scripts/copy-wasm.sh`` on every build, so production installs always
#: have it. Skipping the check disables the only supply-chain defense on
#: the WASM binary; the SDK emits a loud WARNING if this is set.
ENV_SKIP_WASM_INTEGRITY = "CHECKRD_SKIP_WASM_INTEGRITY"

#: Break-glass acknowledgment for running with
#: :data:`ENV_SKIP_WASM_INTEGRITY` in a production-looking environment.
#: The value must be the literal string ``"i-understand-the-risk"`` — a
#: deliberately awkward phrase so nobody sets it by accident. The only
#: legitimate use is an emergency dev/debugging session against a
#: production-like target; in every other case, integrity verification
#: is mandatory. Matches the break-glass override pattern used by
#: Kubernetes (``--accept-hosts``) and Sentry's ``_experiments``.
ENV_ACK_WASM_RISK = "CHECKRD_I_UNDERSTAND_WASM_INTEGRITY_RISK"
ENV_ACK_WASM_RISK_VALUE = "i-understand-the-risk"

#: Environment variables consulted, in order, to infer whether the SDK is
#: running in a production-like deployment. Any one of these set to a
#: value in :data:`_PRODUCTION_ENV_VALUES` locks down security bypasses.
#: Mirrors the signals used by Rails (``RAILS_ENV``), Django
#: (``DJANGO_SETTINGS_MODULE``), Node (``NODE_ENV``), and Sentry's
#: ``environment`` tag — no single value is authoritative, because every
#: framework spells "production" differently.
_PRODUCTION_SIGNAL_ENVS: tuple[str, ...] = (
    "CHECKRD_ENV",
    "CHECKRD_ENVIRONMENT",
    "ENVIRONMENT",
    "ENV",
    "APP_ENV",
    "NODE_ENV",
    "RAILS_ENV",
    "DJANGO_ENV",
    "FLASK_ENV",
    "PYTHON_ENV",
    "DEPLOYMENT_ENVIRONMENT",
)

#: Values (lowercased) on any of :data:`_PRODUCTION_SIGNAL_ENVS` that
#: flag the environment as production-like. "canary" and "live" are
#: included because some teams spell production differently.
_PRODUCTION_ENV_VALUES = frozenset({"production", "prod", "canary", "live"})

#: Deprecated. Previously a single flag bundling HTTP allowance and WASM
#: integrity bypass. Kept as a backwards-compat alias: when set, both
#: :data:`ENV_ALLOW_INSECURE_HTTP` and :data:`ENV_SKIP_WASM_INTEGRITY`
#: are treated as if they were set. Emits a ``DeprecationWarning``.
#:
#: Bundling these two capabilities behind one env var meant a single leaked
#: variable (CI secret, container escape) disabled two independent security
#: controls — the split exists to prevent that.
ENV_DEV = "CHECKRD_DEV"

#: Environment variable controlling fail-closed vs fail-open behavior.
#: Values:
#:
#: - ``strict`` (default): raise :class:`CheckrdInitError` on WASM engine
#:   failure. A broken security layer must not silently allow traffic.
#: - ``permissive``: log a warning and pass traffic through unchecked.
#:   Opt-in for gradual rollout — intended for teams who want to observe
#:   SDK integration issues without their app breaking.
#:
#: Explicit ``security_mode=`` argument on :func:`init`/:func:`wrap` always
#: wins over this env var.
ENV_SECURITY_MODE = "CHECKRD_SECURITY_MODE"

#: Default dashboard base URL.
DEFAULT_DASHBOARD_URL = "https://app.checkrd.io"

#: Default control-plane base URL when an API key is configured but no
#: explicit base URL is given.
DEFAULT_BASE_URL = "https://api.checkrd.io"

#: Type alias for the ``enforce`` parameter of :func:`checkrd.wrap`.
#:
#: Three values:
#:   - ``True``: always block on engine deny. Operator override.
#:   - ``False``: never block; record deny verdicts in telemetry only.
#:     Use for phased rollouts where you want to log "would have been
#:     denied" without breaking real traffic.
#:   - ``"auto"`` (default): trust the engine. Block on engine deny;
#:     since the WASM engine respects the policy's ``mode`` field
#:     internally (``mode: dry_run`` returns allowed=true even on a
#:     deny match), this never over-enforces. Mirrors how every
#:     comparable enforcement point handles it (OPA-PEP, Envoy
#:     ext_authz, Stripe Radar, AWS Config, Cloudflare WAF — policy
#:     carries the mode, the enforcement point trusts the verdict).
EnforceMode = Union[bool, Literal["auto"]]

#: Type alias for the ``security_mode`` parameter of :func:`checkrd.wrap`.
#:
#: - ``strict`` (default): fail-closed — WASM engine errors raise instead of
#:   silently degrading to pass-through. Required for any deployment that
#:   treats Checkrd as a security boundary.
#: - ``permissive``: fail-open — logs a warning and continues without
#:   policy enforcement. Opt-in for gradual rollout only.
SecurityMode = Literal["strict", "permissive"]

#: Default security mode. Fail-closed by default — the security layer
#: must not silently disable itself. Callers opt in to ``"permissive"``
#: during rollout.
DEFAULT_SECURITY_MODE: SecurityMode = "strict"

# PaaS service-name env vars checked in priority order when no explicit
# ``CHECKRD_AGENT_ID`` is set. Ordered by how precisely each one identifies
# a logical service (vs. a physical host or a one-off invocation).
_PAAS_ENV_KEYS: tuple[str, ...] = (
    "FLY_APP_NAME",             # Fly.io
    "K_SERVICE",                # Knative / Google Cloud Run
    "AWS_LAMBDA_FUNCTION_NAME", # AWS Lambda
    "HEROKU_APP_NAME",          # Heroku
    "RAILWAY_SERVICE_NAME",     # Railway
    "RENDER_SERVICE_NAME",      # Render
    "KOYEB_APP_NAME",           # Koyeb
    "FUNCTION_TARGET",          # Google Cloud Functions (2nd gen)
)

# Values accepted as a truthy boolean in env vars. Matches the convention
# used by Stripe, Django, and most Rust services. Anything not in this set
# (and not in _FALSY) means "use the default".
_TRUTHY = frozenset({"1", "true", "yes", "on"})
_FALSY = frozenset({"0", "false", "no", "off", ""})


# ---------------------------------------------------------------------------
# Settings dataclass
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Settings:
    """Resolved SDK settings. Immutable.

    Produced by :func:`resolve`. Every field on this object reflects the
    final value after applying the precedence chain (explicit > env > default),
    so downstream code never has to re-check ``os.environ``.

    Attributes:
        agent_id: The resolved stable agent identifier. Always non-empty.
        api_key: The resolved control-plane API key, or ``None`` if not set.
        control_plane_url: The resolved control-plane base URL, or ``None``
            if neither an API key nor an explicit URL was provided.
        enforce_override: ``True``/``False`` if enforcement was set explicitly
            by the caller or via :data:`ENV_ENFORCE`; ``None`` means
            ``"auto"`` — :func:`checkrd.wrap` decides based on whether a
            policy source was provided.
        disabled: ``True`` if :data:`ENV_DISABLED` is set to a truthy value.
    """

    agent_id: str
    api_key: Optional[str]
    control_plane_url: Optional[str]
    enforce_override: Optional[bool]
    disabled: bool
    dashboard_url: Optional[str]
    debug: bool
    # Defaulted so downstream code that constructs Settings directly (rare —
    # `resolve()` is the public entry point) does not need updating when new
    # fields are added. New fields land at the end for this reason.
    security_mode: SecurityMode = DEFAULT_SECURITY_MODE
    #: Stripe-style date pin sent as ``Checkrd-Version`` on every
    #: control-plane request when non-empty. Lets the control plane
    #: serve old + new clients simultaneously and lets customers pin
    #: a known-good API shape across rollouts. Empty string means
    #: "follow the server default" (which in practice is the latest).
    api_version: str = ""

    @property
    def has_control_plane(self) -> bool:
        """Whether the settings are sufficient to talk to the control plane."""
        return self.api_key is not None and self.control_plane_url is not None


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


#: Environment variable for the Stripe-style date-pinned API version.
#: Matches the ``{PROJECT}_API_VERSION`` convention on Stripe and
#: Anthropic's SDKs. When set, the value is stamped as
#: ``Checkrd-Version`` on every control-plane request.
ENV_API_VERSION = "CHECKRD_API_VERSION"


def resolve(
    *,
    agent_id: Optional[str] = None,
    api_key: Optional[str] = None,
    control_plane_url: Optional[str] = None,
    enforce: EnforceMode = "auto",
    debug: bool = False,
    security_mode: Optional[SecurityMode] = None,
    api_version: Optional[str] = None,
    env: Optional[Mapping[str, str]] = None,
) -> Settings:
    """Resolve SDK settings from explicit args, environment, and derived defaults.

    The returned :class:`Settings` is ready for :func:`checkrd.wrap` to
    consume. Precedence (highest to lowest) is applied per field::

        explicit keyword argument  >  environment variable  >  derived default

    Args:
        agent_id: Explicit agent identifier. Defaults to ``CHECKRD_AGENT_ID``,
            then to :func:`derive_agent_id`.
        api_key: Explicit API key. Defaults to ``CHECKRD_API_KEY``.
        control_plane_url: Explicit control-plane base URL. Defaults to
            ``CHECKRD_BASE_URL``, then to :data:`DEFAULT_BASE_URL` if
            ``api_key`` ended up set.
        enforce: ``True``/``False`` to force the mode, or ``"auto"`` (the
            default) to defer the decision to :func:`checkrd.wrap`. When
            ``"auto"`` is requested, :data:`ENV_ENFORCE` is consulted as a
            fallback.
        env: Optional environment mapping (used by tests to inject isolated
            state). Defaults to ``os.environ``.

    Returns:
        A :class:`Settings` object reflecting the resolved configuration.

    Raises:
        ValueError: If ``enforce`` is not ``True``, ``False``, or ``"auto"``.
    """
    environ: Mapping[str, str] = env if env is not None else os.environ

    disabled = _parse_bool(environ.get(ENV_DISABLED)) or False

    resolved_api_key = api_key if api_key is not None else environ.get(ENV_API_KEY) or None

    if control_plane_url is not None:
        resolved_url: Optional[str] = control_plane_url
    else:
        resolved_url = environ.get(ENV_BASE_URL)
        if not resolved_url and resolved_api_key:
            # Auto-populate when an API key is present so the zero-config
            # path works out of the box against the hosted control plane.
            resolved_url = DEFAULT_BASE_URL
        elif not resolved_url:
            resolved_url = None

    if agent_id is not None:
        resolved_agent_id = agent_id
    else:
        env_agent_id = environ.get(ENV_AGENT_ID)
        if env_agent_id and env_agent_id.strip():
            resolved_agent_id = env_agent_id.strip()
        else:
            resolved_agent_id = derive_agent_id(env=environ)

    enforce_override = _resolve_enforce(enforce, environ)

    resolved_dashboard_url = environ.get(ENV_DASHBOARD_URL) or DEFAULT_DASHBOARD_URL
    resolved_debug = debug or (_parse_bool(environ.get(ENV_DEBUG)) or False)
    resolved_security_mode = _resolve_security_mode(security_mode, environ)

    # Validate URLs: catch bad config at init time, not minutes later when a
    # telemetry batch fails to send with a confusing socket error.
    if resolved_url is not None:
        _validate_url(resolved_url, "control_plane_url", environ)
    if resolved_dashboard_url is not None:
        _validate_url(resolved_dashboard_url, "dashboard_url", environ)

    # Stripe-style ``Checkrd-Version`` pin. Explicit arg > env > "".
    # Empty string means "follow the server default" — consumers
    # omit the header entirely in that case (see
    # :func:`checkrd._platform.default_control_headers`).
    if api_version is not None:
        resolved_api_version = api_version
    else:
        resolved_api_version = environ.get(ENV_API_VERSION, "")

    return Settings(
        agent_id=resolved_agent_id,
        api_key=resolved_api_key,
        control_plane_url=resolved_url,
        enforce_override=enforce_override,
        disabled=disabled,
        dashboard_url=resolved_dashboard_url,
        debug=resolved_debug,
        security_mode=resolved_security_mode,
        api_version=resolved_api_version,
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _validate_url(url: str, param_name: str, environ: Mapping[str, str]) -> None:
    """Validate that a control-plane URL is well-formed and uses HTTPS.

    Rejects:
    - URLs that cannot be parsed (``ValueError``-level garbage).
    - URLs with no scheme or host.
    - Non-HTTPS URLs in production (HTTP, FTP, etc.). Sending API keys
      and signed telemetry over plaintext is a credential leak.

    In dev mode (``CHECKRD_DEV=1``), non-HTTPS URLs are allowed with a
    warning. This supports ``http://localhost:8080`` for local development.
    """
    try:
        parsed = urlparse(url)
    except Exception:
        raise ValueError(
            f"{param_name} is not a valid URL: {url!r}"
        )

    if not parsed.scheme:
        raise ValueError(
            f"{param_name} has no scheme (expected https://...): {url!r}"
        )
    if not parsed.hostname:
        raise ValueError(
            f"{param_name} has no hostname: {url!r}"
        )

    if parsed.scheme.lower() != "https":
        if _http_allowed(environ):
            logger.warning(
                "checkrd: %s uses non-HTTPS scheme %r (allowed because "
                "CHECKRD_ALLOW_INSECURE_HTTP is set). Never use HTTP in "
                "production — API keys and signed telemetry would be sent "
                "in plaintext.",
                param_name,
                parsed.scheme,
            )
            return
        raise ValueError(
            f"{param_name} must use HTTPS, got {parsed.scheme!r} in "
            f"{url!r}. Sending API keys over plaintext HTTP is a "
            f"credential leak. If you are developing locally, set "
            f"CHECKRD_ALLOW_INSECURE_HTTP=1 to allow HTTP."
        )


def _http_allowed(environ: Mapping[str, str]) -> bool:
    """Return True if non-HTTPS control-plane URLs are opted in.

    New-style flag (``CHECKRD_ALLOW_INSECURE_HTTP``) is authoritative.
    Legacy ``CHECKRD_DEV`` is honored with a ``DeprecationWarning`` — it
    used to bundle HTTP + WASM-integrity bypass into one variable; the
    split exists so a single leaked value can't disable both controls.
    """
    if environ.get(ENV_ALLOW_INSECURE_HTTP, "").strip().lower() in _TRUTHY:
        return True
    if environ.get(ENV_DEV, "").strip().lower() in _TRUTHY:
        _warn_dev_deprecated()
        return True
    return False


def _wasm_integrity_skipped(environ: Mapping[str, str]) -> bool:
    """Return True if WASM integrity verification is opted out.

    Refuses the bypass in production-looking environments unless the
    operator explicitly sets
    ``CHECKRD_I_UNDERSTAND_WASM_INTEGRITY_RISK=i-understand-the-risk``.
    The awkward acknowledgment phrase is deliberate — this flag exists
    to catch accidents (a dev env var leaking into a prod deploy), not
    to block every possible use case.

    Raises:
        CheckrdInitError: when the skip flag is set in a production-like
            environment without the acknowledgment. The message is the
            only reasonable resolution path: either unset the flag or
            add the acknowledgment env var.
    """
    requested = (
        environ.get(ENV_SKIP_WASM_INTEGRITY, "").strip().lower() in _TRUTHY
    )
    legacy = environ.get(ENV_DEV, "").strip().lower() in _TRUTHY
    if not (requested or legacy):
        return False
    if legacy:
        _warn_dev_deprecated()
    if _looks_production(environ) and not _wasm_risk_acknowledged(environ):
        # Import locally to avoid a circular import with exceptions.py at
        # module load time.
        from checkrd.exceptions import CheckrdInitError

        signal = _production_signal(environ)
        if signal is None:
            # _looks_production returned True but _production_signal didn't
            # find one — invariant violation. Raise rather than silently
            # downgrade, since this is the WASM-integrity-skip code path.
            raise RuntimeError(
                "internal invariant: _looks_production() True but "
                "_production_signal() returned None"
            )
        signal_env, signal_value = signal
        raise CheckrdInitError(
            "CHECKRD_SKIP_WASM_INTEGRITY is set in a production-looking "
            f"environment ({signal_env}={signal_value!r}). This would "
            "disable the only supply-chain defense on the WASM binary. "
            "Either:\n"
            "  1. Unset CHECKRD_SKIP_WASM_INTEGRITY (recommended — the "
            "hash file is regenerated on every build), OR\n"
            f"  2. Set {ENV_ACK_WASM_RISK}={ENV_ACK_WASM_RISK_VALUE!r} "
            "if this is an intentional emergency debugging session.\n"
            "See https://checkrd.io/errors/wasm_integrity_skip_in_prod"
        )
    return True


def _looks_production(environ: Mapping[str, str]) -> bool:
    """Return True if any common env-name convention flags production."""
    return _production_signal(environ) is not None


def _production_signal(
    environ: Mapping[str, str],
) -> Optional[tuple[str, str]]:
    """Return the (env_name, raw_value) pair that flagged production, if any."""
    for name in _PRODUCTION_SIGNAL_ENVS:
        raw = environ.get(name, "")
        if raw.strip().lower() in _PRODUCTION_ENV_VALUES:
            return name, raw.strip()
    return None


def _wasm_risk_acknowledged(environ: Mapping[str, str]) -> bool:
    """True iff the operator typed the break-glass acknowledgment phrase.

    Exact-match comparison (no trim, no case-fold). The phrase is a
    deliberate muscle-memory barrier, not a configuration knob — any
    tolerance for near-misses erodes that barrier. If an operator is
    copy-pasting with trailing whitespace or uppercasing the phrase,
    they are probably scripting around a safety check, which is
    exactly the scenario the phrase exists to catch.
    """
    return environ.get(ENV_ACK_WASM_RISK, "") == ENV_ACK_WASM_RISK_VALUE


_dev_warning_emitted = False


def _warn_dev_deprecated() -> None:
    """Emit DeprecationWarning for legacy CHECKRD_DEV env var (once per process)."""
    global _dev_warning_emitted  # noqa: PLW0603
    if _dev_warning_emitted:
        return
    _dev_warning_emitted = True
    import warnings
    warnings.warn(
        "CHECKRD_DEV is deprecated and will be removed in 1.0. "
        "It bundled two independent security controls behind one flag. "
        "Use CHECKRD_ALLOW_INSECURE_HTTP=1 (allows http:// URLs) and/or "
        "CHECKRD_SKIP_WASM_INTEGRITY=1 (test-only) instead.",
        DeprecationWarning,
        stacklevel=3,
    )


def _resolve_security_mode(
    explicit: Optional["SecurityMode"],
    environ: Mapping[str, str],
) -> "SecurityMode":
    """Collapse the security_mode argument into a resolved value.

    Precedence: explicit keyword argument > env var > default (``strict``).
    Unknown env-var values fall back to the default (not silent permissive),
    so a typo can never weaken the security posture.
    """
    if explicit is not None:
        if explicit not in ("strict", "permissive"):
            raise ValueError(
                f"security_mode must be 'strict' or 'permissive'; "
                f"got {explicit!r}"
            )
        return explicit
    raw = environ.get(ENV_SECURITY_MODE, "").strip().lower()
    if raw == "permissive":
        return "permissive"
    if raw == "strict":
        return "strict"
    if raw and raw not in ("strict", "permissive"):
        logger.warning(
            "checkrd: unrecognized %s=%r, falling back to %r (fail-closed).",
            ENV_SECURITY_MODE,
            raw,
            DEFAULT_SECURITY_MODE,
        )
    return DEFAULT_SECURITY_MODE


def _resolve_enforce(
    enforce: EnforceMode,
    environ: Mapping[str, str],
) -> Optional[bool]:
    """Collapse the ``enforce`` argument into an explicit override or ``None``.

    An explicit ``True``/``False`` from the caller always wins — env vars
    cannot silently turn enforcement off in code that asked for it. ``"auto"``
    is the only value that falls back to the env var, which in turn falls
    back to ``None`` (meaning "let wrap() decide").
    """
    if enforce is True:
        return True
    if enforce is False:
        return False
    if enforce == "auto":
        raw = environ.get(ENV_ENFORCE)
        if raw is None:
            return None
        parsed = _parse_bool(raw)
        return parsed  # None if unrecognized value -> "auto" fallback
    raise ValueError(
        f"enforce must be True, False, or 'auto'; got {enforce!r}"
    )


def _parse_bool(value: Optional[str]) -> Optional[bool]:
    """Parse a standard truthy/falsy env-var string.

    Returns ``None`` for values outside the recognized sets so callers can
    distinguish "explicitly false" from "unset or garbled". This lets the
    default path remain predictable even when an operator mis-spells
    ``CHECKRD_ENFORCE=yess``.
    """
    if value is None:
        return None
    normalized = value.strip().lower()
    if normalized in _TRUTHY:
        return True
    if normalized in _FALSY:
        return False
    return None


def derive_agent_id(env: Optional[Mapping[str, str]] = None) -> str:
    """Derive a stable agent identifier from the deployment environment.

    Tries in order:

    1. PaaS service-name environment variables (Fly, Cloud Run, Lambda,
       Heroku, Railway, Render, Koyeb, Google Cloud Functions).
    2. ``{script_name}-{short_hostname}`` — stable per host, good enough
       for bare-metal and containers with a meaningful hostname.

    Raises :class:`CheckrdInitError` if neither path produces a stable
    identifier. **This is fail-closed by design.** A random-UUID
    fallback would silently produce a different ``agent_id`` on every
    process restart in containers with randomized hostnames, which
    breaks every downstream identity guarantee:

    - Per-agent kill-switch scoping evaporates (the new identity is not
      what the operator paged on).
    - Telemetry signature verification fails server-side because the
      registered public key belongs to a different ``agent_id``.
    - Dashboards group on the volatile id, fragmenting history across
      restarts.

    Operators in environments without a stable hostname or PaaS env var
    must set :data:`ENV_AGENT_ID` (``CHECKRD_AGENT_ID``) explicitly. The
    error message names every workable option so the fix is mechanical.

    Args:
        env: Environment mapping. Defaults to ``os.environ`` for the
            normal path, overridable for tests.

    Returns:
        The derived agent identifier. Always non-empty.

    Raises:
        CheckrdInitError: when no deterministic identifier can be
            derived. ``code="agent_id_undetectable"``.
    """
    environ: Mapping[str, str] = env if env is not None else os.environ

    for key in _PAAS_ENV_KEYS:
        value = environ.get(key)
        if value and value.strip():
            return value.strip()

    hostname = _short_hostname()
    script_name = Path(sys.argv[0] or "python").stem or "python"
    if hostname:
        return f"{script_name}-{hostname}"

    # No PaaS service name, no hostname — refuse to invent one.
    # Local import: ``derive_agent_id`` runs during ``resolve()`` which
    # other modules pull in eagerly; importing CheckrdInitError at module
    # top would risk a circular import.
    from checkrd.exceptions import CheckrdInitError

    paas_keys = ", ".join(_PAAS_ENV_KEYS)
    raise CheckrdInitError(
        "checkrd: cannot derive a stable agent_id — neither the system "
        "hostname nor any known PaaS service-name env var is set. "
        "A random fallback would change on every process restart, "
        "breaking kill-switch scoping and telemetry signature verification. "
        f"Set {ENV_AGENT_ID} explicitly, or run on a platform that "
        f"populates one of: {paas_keys}.",
        code="agent_id_undetectable",
    )


def _short_hostname() -> str:
    """Return the short hostname (before the first dot), or ``""`` on failure.

    ``socket.gethostname()`` can raise ``OSError`` in bizarre container
    environments; we treat any failure as "no hostname available" rather
    than surfacing it through the init path.
    """
    try:
        name = socket.gethostname()
    except OSError:
        return ""
    if not name:
        return ""
    return name.split(".", 1)[0]
