"""WASM engine bridge for Checkrd core."""

from __future__ import annotations

import hashlib
import json
import logging
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union

import wasmtime

from checkrd.exceptions import CheckrdInitError, PolicySignatureError

logger = logging.getLogger("checkrd")

_WASM_PATH = Path(__file__).parent / "checkrd_core.wasm"

# The wasmtime Engine and compiled Module are thread-safe and expensive to create.
# Cache them globally so multiple WasmEngine instances (multiple wrapped clients)
# reuse the same compiled module. Only the Store is per-instance.
_module_cache_lock = threading.Lock()
_cached_wasm_engine: Optional[wasmtime.Engine] = None
_cached_module: Optional[wasmtime.Module] = None


def _verify_wasm_integrity(wasm_path: Path) -> None:
    """Verify SHA-256 of the WASM binary against the build-time hash.

    The hash file ``_wasm_integrity.py`` is generated by ``scripts/copy-wasm.sh``.

    **Fail-closed by default:** When the hash file is missing, the function
    raises ``CheckrdInitError`` — a packaging or deployment error should not
    silently disable the only supply-chain defense on the WASM binary. A
    tampered binary could allow-all (bypass policy), deny-all (DoS), or
    forge telemetry signatures.

    The exception is **dev mode** (``CHECKRD_DEV=1``): contributors running
    ``pip install -e .`` with a manually copied WASM binary will not have
    the hash file. In that case a warning is logged and verification is
    skipped. ``CHECKRD_DEV`` should never be set in production — the SDK
    logs a warning when it is active.
    """
    import os

    from checkrd._settings import _wasm_integrity_skipped

    if _wasm_integrity_skipped(os.environ):
        logger.warning(
            "checkrd: WASM integrity verification SKIPPED "
            "(CHECKRD_SKIP_WASM_INTEGRITY is set). This is the only "
            "supply-chain defense on the WASM binary — never enable "
            "this flag in production."
        )
        return

    try:
        from checkrd._wasm_integrity import EXPECTED_SHA256
    except ImportError:
        raise CheckrdInitError(
            "WASM binary integrity file (_wasm_integrity.py) is missing. "
            "This file is required for supply-chain verification of the "
            "WASM binary. Reinstall the package (`pip install checkrd`) "
            "or rebuild with `scripts/copy-wasm.sh`. For local development "
            "from a source checkout, set CHECKRD_SKIP_WASM_INTEGRITY=1 "
            "(test-only — never in production)."
        )

    actual = hashlib.sha256(wasm_path.read_bytes()).hexdigest()
    if actual != EXPECTED_SHA256:
        raise CheckrdInitError(
            f"WASM binary integrity check failed.\n"
            f"  expected: {EXPECTED_SHA256}\n"
            f"  actual:   {actual}\n"
            f"The file at {wasm_path} may have been tampered with. "
            f"Reinstall the package or rebuild with scripts/copy-wasm.sh."
        )


def _get_module() -> tuple[wasmtime.Engine, wasmtime.Module]:
    global _cached_wasm_engine, _cached_module  # noqa: PLW0603

    # Always acquire the lock — no pre-lock fast path.
    # The double-checked locking pattern (reading globals outside the lock)
    # is unsafe under PEP 703 free-threading: a thread could see a non-None
    # _cached_module but a stale _cached_wasm_engine due to CPU/compiler
    # reordering. The lock is only contended once (during first load), so
    # the overhead is negligible.
    with _module_cache_lock:
        if _cached_module is not None and _cached_wasm_engine is not None:
            return _cached_wasm_engine, _cached_module

        wasm_path = _WASM_PATH
        if not wasm_path.exists():
            raise CheckrdInitError(
                f"WASM module not found at {wasm_path}. "
                "Run ./scripts/build-wasm.sh && ./scripts/copy-wasm.sh first."
            )

        # Supply-chain integrity check: verify the WASM binary hasn't been
        # tampered with since build time. A compromised binary could allow-all
        # (bypass policy), deny-all (DoS), or forge telemetry/signatures.
        _verify_wasm_integrity(wasm_path)

        try:
            engine = wasmtime.Engine()
            module = wasmtime.Module.from_file(engine, str(wasm_path))
        except Exception as e:
            raise CheckrdInitError(f"Failed to load WASM module: {e}") from e

        _cached_wasm_engine = engine
        _cached_module = module
        return engine, module


@dataclass(frozen=True)
class EvalResult:
    """Result of evaluating a request against the policy engine."""

    allowed: bool
    deny_reason: Optional[str]
    telemetry_json: str
    request_id: str


class WasmEngine:
    """Bridge to the Checkrd WASM core via wasmtime.

    Each instance owns a wasmtime Store. All access to the Store is
    serialized by ``_lock`` because wasmtime's Store is **not**
    thread-safe. When the engine is shared (via ``checkrd.init()`` +
    ``checkrd.instrument()``), multiple threads call ``evaluate()``
    while background threads call ``sign_telemetry_batch()``,
    ``set_kill_switch()``, and ``reload_policy()``.

    The lock is a standard ``threading.Lock`` — not an RLock — because
    no public method calls another public method (no re-entrance risk).
    """

    def __init__(
        self,
        policy_json: str,
        agent_id: str,
        private_key_bytes: Union[bytes, bytearray] = b"",
        instance_id: str = "",
    ) -> None:
        self._lock = threading.Lock()

        wasm_engine, module = _get_module()

        try:
            self._store = wasmtime.Store(wasm_engine)
            wasi_config = wasmtime.WasiConfig()
            self._store.set_wasi(wasi_config)

            linker = wasmtime.Linker(wasm_engine)
            linker.define_wasi()
            instance = linker.instantiate(self._store, module)
        except Exception as e:
            raise CheckrdInitError(f"Failed to instantiate WASM module: {e}") from e

        # wasmtime exports return union types that mypy can't narrow to callable.
        # These are always Func objects at runtime for our WASM module.
        exports: Any = instance.exports(self._store)
        self._memory: wasmtime.Memory = exports["memory"]
        self._alloc: Any = exports["alloc"]
        self._dealloc: Any = exports["dealloc"]
        self._init_fn: Any = exports["init"]
        self._evaluate_fn: Any = exports["evaluate_request"]
        self._kill_switch_fn: Any = exports["set_kill_switch"]
        self._reload_fn: Any = exports["reload_policy"]
        self._reload_signed_fn: Any = exports["reload_policy_signed"]
        self._get_active_policy_version_fn: Any = exports["get_active_policy_version"]
        self._set_initial_policy_version_fn: Any = exports["set_initial_policy_version"]
        self._generate_keypair_fn: Any = exports["generate_keypair"]
        self._sign_fn: Any = exports["sign"]
        self._sign_telemetry_batch_fn: Any = exports["sign_telemetry_batch"]
        self._derive_public_key_fn: Any = exports["derive_public_key"]

        rc = self._call_init(
            policy_json, agent_id, bytes(private_key_bytes), instance_id
        )
        if rc != 0:
            codes = {-1: "invalid policy JSON", -2: "invalid UTF-8", -3: "invalid key length"}
            raise CheckrdInitError(f"WASM init() failed: {codes.get(rc, f'error code {rc}')}")

    def evaluate(
        self,
        request_id: str,
        method: str,
        url: str,
        headers: list[tuple[str, str]],
        body: Optional[str],
        timestamp: str,
        timestamp_ms: int,
        trace_id: Optional[str] = None,
        span_id: Optional[str] = None,
        parent_span_id: Optional[str] = None,
    ) -> EvalResult:
        """Evaluate a request against the loaded policy.

        Returns an EvalResult with the allow/deny decision and telemetry event JSON.
        """
        request_dict: dict[str, Any] = {
            "request_id": request_id,
            "method": method,
            "url": url,
            "headers": headers,
            "body": body,
            "timestamp": timestamp,
            "timestamp_ms": timestamp_ms,
            "trace_id": trace_id or "",
            "span_id": span_id or "",
            "parent_span_id": parent_span_id,
        }
        request_json = json.dumps(request_dict)

        start = time.perf_counter_ns()

        with self._lock:
            req_ptr, req_len = self._write_to_wasm(request_json)
            try:
                packed: int = self._evaluate_fn(self._store, req_ptr, req_len)
            finally:
                self._dealloc(self._store, req_ptr, req_len)

            result_ptr, result_len = self._unpack(packed)
            result_json = self._read_from_wasm(result_ptr, result_len)
            self._dealloc(self._store, result_ptr, result_len)

        eval_us = (time.perf_counter_ns() - start) / 1000
        logger.debug("checkrd: evaluate %s %s -> %.0fμs", method, url, eval_us)

        result = json.loads(result_json)

        return EvalResult(
            allowed=result["allowed"],
            deny_reason=result.get("deny_reason"),
            telemetry_json=result.get("log_event_json", "{}"),
            request_id=result["request_id"],
        )

    def set_kill_switch(self, active: bool) -> None:
        """Toggle the kill switch. When active, all requests are denied."""
        with self._lock:
            self._kill_switch_fn(self._store, 1 if active else 0)

    def sign(self, payload: bytes) -> bytes:
        """Sign a payload using the engine's Ed25519 identity key.

        Returns the 64-byte signature, or empty bytes if the engine was
        initialized without a private key (anonymous/KMS mode).
        """
        with self._lock:
            ptr, length = self._write_bytes_to_wasm(payload)
            try:
                packed: int = self._sign_fn(self._store, ptr, length)
            finally:
                if length > 0:
                    self._dealloc(self._store, ptr, length)
            if packed == 0:
                return b""
            sig_ptr, sig_len = self._unpack(packed)
            sig = self._memory.read(self._store, sig_ptr, sig_ptr + sig_len)
            self._dealloc(self._store, sig_ptr, sig_len)
            return bytes(sig)

    def sign_telemetry_batch(
        self,
        *,
        batch_json: bytes,
        target_uri: str,
        signer_agent: str,
        nonce: str,
        created: int,
        expires: int,
    ) -> Optional[dict[str, Any]]:
        """Sign a telemetry batch via the WASM core.

        Produces both an RFC 9421 HTTP Message Signature and a DSSE envelope
        that the ingestion service can verify against the agent's registered
        public key. The wrapper supplies the wall-clock timestamp and nonce
        because the WASM core has no access to a clock or RNG.

        Returns a dict with these keys when signing succeeds:
        - ``content_digest``: ``Content-Digest`` header value (RFC 9530)
        - ``signature_input``: ``Signature-Input`` header value (RFC 9421)
        - ``signature``: ``Signature`` header value (RFC 9421)
        - ``dsse_envelope``: DSSE envelope JSON (forwarded into SQS for the
          telemetry-writer to re-verify before persisting to Aurora)
        - ``instance_id``: 16-hex-char fingerprint of the public key
        - ``expires``: echoed expiration timestamp

        Returns ``None`` when the engine has no signing key (anonymous mode
        or external KMS provider). Callers should fall back to unsigned
        ingestion in that case.
        """
        with self._lock:
            batch_ptr, batch_len = self._write_bytes_to_wasm(batch_json)
            target_ptr, target_len = self._write_to_wasm(target_uri)
            agent_ptr, agent_len = self._write_to_wasm(signer_agent)
            nonce_ptr, nonce_len = self._write_to_wasm(nonce)
            try:
                packed: int = self._sign_telemetry_batch_fn(
                    self._store,
                    batch_ptr,
                    batch_len,
                    target_ptr,
                    target_len,
                    agent_ptr,
                    agent_len,
                    nonce_ptr,
                    nonce_len,
                    created,
                    expires,
                )
            finally:
                if batch_len > 0:
                    self._dealloc(self._store, batch_ptr, batch_len)
                self._dealloc(self._store, target_ptr, target_len)
                self._dealloc(self._store, agent_ptr, agent_len)
                self._dealloc(self._store, nonce_ptr, nonce_len)

            if packed == 0:
                return None
            result_ptr, result_len = self._unpack(packed)
            result_json = self._read_from_wasm(result_ptr, result_len)
            self._dealloc(self._store, result_ptr, result_len)
        return json.loads(result_json)  # type: ignore[no-any-return]

    def reload_policy(self, policy_json: str) -> None:
        """Hot-reload policy without reinitializing. Resets rate limit counters."""
        with self._lock:
            ptr, length = self._write_to_wasm(policy_json)
            try:
                rc: int = self._reload_fn(self._store, ptr, length)
            finally:
                self._dealloc(self._store, ptr, length)
        if rc != 0:
            raise CheckrdInitError("reload_policy() failed. Check policy JSON format.")

    def reload_policy_signed(
        self,
        envelope_json: str,
        trusted_keys_json: str,
        now_unix_secs: int,
        max_age_secs: int,
    ) -> None:
        """Hot-reload policy from a DSSE-signed envelope.

        Verifies the envelope against the supplied trust list via the WASM
        core's ``reload_policy_signed`` FFI export and enforces every defense:

        - DSSE signature verification against trusted keys
        - Monotonic version check (rollback rejection)
        - Bundle freshness check via ``signed_at`` field within ``max_age_secs``
        - Cross-type replay defense via DSSE payload type binding

        On any failure, the existing policy is left in place and
        ``PolicySignatureError`` is raised — the engine never silently
        installs an unverified or stale policy.

        # Arguments

        - ``envelope_json``: DSSE envelope JSON as received from the control plane.
          The verified payload must be a `PolicyBundle` JSON document.
        - ``trusted_keys_json``: JSON array of trusted Ed25519 public keys with
          validity windows. See ``checkrd._trust.trusted_policy_keys()``.
        - ``now_unix_secs``: current Unix timestamp; injected by the caller
          because the WASM core has no clock access.
        - ``max_age_secs``: maximum bundle age accepted. Bundles whose
          ``signed_at`` is more than this many seconds in the past are
          rejected as stale.

        # Raises

        - ``PolicySignatureError`` with the FFI error code on any verification,
          monotonicity, or freshness failure.
        """
        with self._lock:
            env_ptr, env_len = self._write_to_wasm(envelope_json)
            keys_ptr, keys_len = self._write_to_wasm(trusted_keys_json)
            try:
                rc: int = self._reload_signed_fn(
                    self._store,
                    env_ptr,
                    env_len,
                    keys_ptr,
                    keys_len,
                    now_unix_secs,
                    max_age_secs,
                )
            finally:
                self._dealloc(self._store, env_ptr, env_len)
                self._dealloc(self._store, keys_ptr, keys_len)
        if rc != 0:
            raise PolicySignatureError(rc)

    def get_active_policy_version(self) -> int:
        """Return the highest policy bundle version this engine has installed.

        Returns 0 before any signed bundle has been installed in this process.
        Used by the SDK's persistence loop: after every successful signed
        install, the wrapper reads this value and atomically writes it to
        ``~/.checkrd/policy_state.json`` so the rollback defense survives
        process restarts.
        """
        with self._lock:
            return int(self._get_active_policy_version_fn(self._store))

    def set_initial_policy_version(self, version: int) -> None:
        """Restore the persisted policy bundle version high water mark.

        Called exactly once during SDK startup, BEFORE any signed reload, to
        feed back the value persisted on the previous run. Without this, an
        attacker who can restart the SDK process trivially defeats rollback
        protection by replaying an older signed bundle (the in-memory
        ``last_policy_version`` would reset to 0).

        This is the same Trust-On-First-Use (TOFU) pattern The Update
        Framework (TUF) uses for client-side metadata version tracking and
        the same pattern OPA uses for bundle revisions.

        Strict semantics enforced by the WASM core:
        - Only succeeds when the engine has not yet installed any signed
          bundle in this process (``last_policy_version == 0``).
        - Cannot be used to roll the counter backwards once a real install
          has happened — once the counter is non-zero, only the monotonic
          ``reload_policy_signed`` path can change it.

        Raises ``CheckrdInitError`` on failure (engine not initialized, or
        a real install has already taken place).
        """
        from checkrd.exceptions import _FFI_ERROR_REASONS

        with self._lock:
            rc: int = self._set_initial_policy_version_fn(self._store, version)
        if rc != 0:
            reason = _FFI_ERROR_REASONS.get(rc, f"unknown_{rc}")
            raise CheckrdInitError(
                f"set_initial_policy_version({version}) failed: "
                f"{reason} (code={rc})"
            )

    # --- WASM memory helpers ---

    def _write_to_wasm(self, data: str) -> tuple[int, int]:
        encoded = data.encode("utf-8")
        length = len(encoded)
        ptr: int = self._alloc(self._store, length)
        self._memory.write(self._store, encoded, ptr)
        return ptr, length

    def _read_from_wasm(self, ptr: int, length: int) -> str:
        data = self._memory.read(self._store, ptr, ptr + length)
        return data.decode("utf-8")

    @staticmethod
    def _unpack(packed: int) -> tuple[int, int]:
        ptr = (packed >> 32) & 0xFFFFFFFF
        length = packed & 0xFFFFFFFF
        return ptr, length

    def _call_init(
        self,
        policy_json: str,
        agent_id: str,
        private_key_bytes: bytes = b"",
        instance_id: str = "",
    ) -> int:
        p_ptr, p_len = self._write_to_wasm(policy_json)
        a_ptr, a_len = self._write_to_wasm(agent_id)
        k_ptr, k_len = self._write_bytes_to_wasm(private_key_bytes)
        i_ptr, i_len = self._write_to_wasm(instance_id)
        try:
            rc: int = self._init_fn(
                self._store,
                p_ptr,
                p_len,
                a_ptr,
                a_len,
                k_ptr,
                k_len,
                i_ptr,
                i_len,
            )
        finally:
            self._dealloc(self._store, p_ptr, p_len)
            self._dealloc(self._store, a_ptr, a_len)
            if k_len > 0:
                self._dealloc(self._store, k_ptr, k_len)
            if i_len > 0:
                self._dealloc(self._store, i_ptr, i_len)
        return rc

    def _write_bytes_to_wasm(self, data: Union[bytes, bytearray]) -> tuple[int, int]:
        if not data:
            return 0, 0
        length = len(data)
        ptr: int = self._alloc(self._store, length)
        self._memory.write(self._store, data, ptr)
        return ptr, length

    @classmethod
    def derive_public_key(cls, private_key: bytes) -> bytes:
        """Derive the Ed25519 public key from a 32-byte private key.

        Used to validate key files after loading (ensure the stored public
        key matches the private key).
        """
        wasm_engine, module = _get_module()
        store = wasmtime.Store(wasm_engine)
        wasi_config = wasmtime.WasiConfig()
        store.set_wasi(wasi_config)
        linker = wasmtime.Linker(wasm_engine)
        linker.define_wasi()
        instance = linker.instantiate(store, module)

        exports: Any = instance.exports(store)
        memory: wasmtime.Memory = exports["memory"]
        alloc_fn: Any = exports["alloc"]
        dealloc_fn: Any = exports["dealloc"]
        derive_fn: Any = exports["derive_public_key"]

        length = len(private_key)
        ptr: int = alloc_fn(store, length)
        memory.write(store, private_key, ptr)
        packed: int = derive_fn(store, ptr, length)
        dealloc_fn(store, ptr, length)

        if packed == 0:
            raise CheckrdInitError("Invalid private key length for public key derivation")

        pk_ptr = (packed >> 32) & 0xFFFFFFFF
        pk_len = packed & 0xFFFFFFFF
        data = memory.read(store, pk_ptr, pk_ptr + pk_len)
        dealloc_fn(store, pk_ptr, pk_len)
        return bytes(data)

    @classmethod
    def generate_keypair(cls) -> tuple[bytes, bytes]:
        """Generate a new Ed25519 keypair via the WASM core.

        Returns (private_key, public_key) as 32-byte byte strings.
        Uses the cached WASM module -- no ``init()`` required.
        """
        wasm_engine, module = _get_module()
        store = wasmtime.Store(wasm_engine)
        wasi_config = wasmtime.WasiConfig()
        store.set_wasi(wasi_config)
        linker = wasmtime.Linker(wasm_engine)
        linker.define_wasi()
        instance = linker.instantiate(store, module)

        exports: Any = instance.exports(store)
        memory: wasmtime.Memory = exports["memory"]
        dealloc: Any = exports["dealloc"]
        generate_fn: Any = exports["generate_keypair"]

        packed: int = generate_fn(store)
        ptr = (packed >> 32) & 0xFFFFFFFF
        length = packed & 0xFFFFFFFF
        data = memory.read(store, ptr, ptr + length)
        dealloc(store, ptr, length)

        return bytes(data[:32]), bytes(data[32:])
