from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.auto_fix import AutoFix


T = TypeVar("T", bound="AnalyzeFinding")


@_attrs_define
class AnalyzeFinding:
    """One enriched finding from static policy analysis.

    Attributes:
        severity (str): `"warning"` or `"error"`. Matches the upstream
            `PolicyWarning::severity`.
        code (str): Machine-readable warning code (1:1 with `PolicyWarning::kind`).
            Examples: `"redundant_rule"`, `"shadowed_rule"`,
            `"overly_broad_allow"`.
        message (str): Human-readable explanation, shaped for direct display in the
            dashboard.
        rule_name (None | str | Unset): Name of the offending rule, when the finding is rule-scoped.
            `None` for config-level findings (e.g. `"(default)"` warnings).
        line (int | None | Unset): 1-based line number of the offending rule in the submitted
            YAML. `None` when the line cannot be located (e.g. config-
            level warnings, or the rule was generated by templating).
        auto_fix (AutoFix | None | Unset):
    """

    severity: str
    code: str
    message: str
    rule_name: None | str | Unset = UNSET
    line: int | None | Unset = UNSET
    auto_fix: AutoFix | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.auto_fix import AutoFix

        severity = self.severity

        code = self.code

        message = self.message

        rule_name: None | str | Unset
        if isinstance(self.rule_name, Unset):
            rule_name = UNSET
        else:
            rule_name = self.rule_name

        line: int | None | Unset
        if isinstance(self.line, Unset):
            line = UNSET
        else:
            line = self.line

        auto_fix: dict[str, Any] | None | Unset
        if isinstance(self.auto_fix, Unset):
            auto_fix = UNSET
        elif isinstance(self.auto_fix, AutoFix):
            auto_fix = self.auto_fix.to_dict()
        else:
            auto_fix = self.auto_fix

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "severity": severity,
                "code": code,
                "message": message,
            }
        )
        if rule_name is not UNSET:
            field_dict["rule_name"] = rule_name
        if line is not UNSET:
            field_dict["line"] = line
        if auto_fix is not UNSET:
            field_dict["auto_fix"] = auto_fix

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.auto_fix import AutoFix

        d = dict(src_dict)
        severity = d.pop("severity")

        code = d.pop("code")

        message = d.pop("message")

        def _parse_rule_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        rule_name = _parse_rule_name(d.pop("rule_name", UNSET))

        def _parse_line(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        line = _parse_line(d.pop("line", UNSET))

        def _parse_auto_fix(data: object) -> AutoFix | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                auto_fix_type_1 = AutoFix.from_dict(data)

                return auto_fix_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(AutoFix | None | Unset, data)

        auto_fix = _parse_auto_fix(d.pop("auto_fix", UNSET))

        analyze_finding = cls(
            severity=severity,
            code=code,
            message=message,
            rule_name=rule_name,
            line=line,
            auto_fix=auto_fix,
        )

        analyze_finding.additional_properties = d
        return analyze_finding

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
