#!/usr/bin/env bash
set -euo pipefail

WASM_FILE="target/wasm32-wasip1/release/checkrd_core.wasm"

if [ ! -f "$WASM_FILE" ]; then
  echo "Error: $WASM_FILE not found. Run scripts/build-wasm.sh first."
  exit 1
fi

echo "Copying .wasm to wrapper packages..."
cp "$WASM_FILE" wrappers/python/src/checkrd/checkrd_core.wasm
cp "$WASM_FILE" wrappers/javascript/checkrd_core.wasm

# Generate SHA-256 integrity hash for supply-chain verification.
# The Python SDK verifies this at load time to detect tampered binaries.
HASH=$(shasum -a 256 "$WASM_FILE" | cut -d' ' -f1)
echo "WASM SHA-256: $HASH"

cat > wrappers/python/src/checkrd/_wasm_integrity.py << EOF
# Auto-generated by scripts/copy-wasm.sh — do not edit.
# SHA-256 of checkrd_core.wasm, verified at WASM load time.
EXPECTED_SHA256 = "$HASH"
EOF

cat > wrappers/javascript/src/_wasm_integrity.ts << EOF
// Auto-generated by scripts/copy-wasm.sh — do not edit.
// SHA-256 of checkrd_core.wasm, verified at WASM load time.
export const EXPECTED_SHA256 = "$HASH";
EOF

echo "Done."
